## YAML Template.
---

name: zP-Brains
version: 1.02
load: STARTUP
author: zP
main: solarsystem.coffee.zPBrainPlugin
softdepend: [Vault, Essentials]
api-version: 1.18

commands:
  airequest:
    description: /ai-request "Write A Request Here"
    permission: Brains.openai
  personality:
    description: /personality number
    permission: Brains.openai
