## YAML Template.
---

name: zP_Brain-plugin
version: 1.01
load: STARTUP
author: zP
main: solarsystem.coffee.zPBrainPlugin
softdepend: [Vault, Essentials]
api-version: 1.18

commands:
  luz:
    description: /luz Mage ability, cast Light
    permission: Brains.zP.luz
  airequest:
    description: /ai-request "Write A Request Here"
    permission: Brains.openai
  personality:
    description: /personality number
    permission: Brains.openai
